## Matrix Operations


In [28]:
### Matrix Operations  
import numpy as np
A=np.array([[1,2], [7,8]]) #abhi
B=np.array([[19,8], [13,4]]) #sind
print(A)
print(B)

[[1 2]
 [7 8]]
[[19  8]
 [13  4]]


## Matrix Addition  


In [5]:
A_plus_B = A + B
print(A_plus_B)

[[20 10]
 [20 12]]


## Matrix Multiplication


In [6]:
A_times_B=np.dot(A,B)
print(A_times_B)

[[ 45  16]
 [237  88]]


## Hadamard Product  


In [11]:
A_Hadamard_B=A*B  
print(A_Hadamard_B)

[[19 16]
 [91 32]]


## Outer Product  


In [8]:
A_outer_B=np.outer(A,B)
print(A_outer_B)

[[ 19   8  13   4]
 [ 38  16  26   8]
 [133  56  91  28]
 [152  64 104  32]]


## Kronocker Product  


In [13]:
A_kronocker_B=np.kron(A,B)
print(A_kronocker_B)

[[ 19   8  38  16]
 [ 13   4  26   8]
 [133  56 152  64]
 [ 91  28 104  32]]


### Question 2  
## Linear algerbra operations using `Numpy` and `sympy`

In [25]:
c=np.array([[2,5], [1,3],[4,-3]])

## Inverse Of a Matix  


In [26]:
C_inv=np.linalg.pinv(c)
print(C_inv)

[[ 0.08980044  0.0443459   0.1940133 ]
 [ 0.11419069  0.06873614 -0.07427938]]


Only Square matrix can be inversed by `np.linalg.inv()`.  
For Other matrix which is not a square matrix we can pesudo inverse by using `np.linalg.pinv()`

In [ ]:
# using sympy
import sympy as sp 
c=

## Determinant Using `Numpy`  

In [29]:
A=np.array([[4,7,2], [1,2,3], [2,6,8]])
det_A = np.linalg.det(A)
print(det_A)

-18.000000000000004


## Eigen values and vectors  


In [33]:
import numpy as np  
B = np.array([[1,2,3,4,5], [6,7,8,9,10], [2,3,4,5,6], [3,5,4,6,8]])
eigenvalues, eigenvectors = np.linalg.eig(B)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

LinAlgError: Last 2 dimensions of the array must be square