## Numpy functions for linear Algebra


Let’s start with some basic matrix operations. Suppose we have two matrices,$A$  and $B$, and we want to add them together. In NumPy, we can do this with the simple command, $A+B$. Let’s look into the detailed computational steps.

In [2]:
import numpy as np
# Addition and Subtraction
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1 + matrix2) # prints [[6, 8], [10, 12]]

[[ 6  8]
 [10 12]]


In [2]:
c=2*matrix1+5*matrix2+np.dot(matrix1,matrix2)
print("Output of thr operation is \n")
print(c)

Output of thr operation is 

[[46 56]
 [84 98]]


## Matrix Substraction
Similary, matrix difference and other matrix operations can be illustrated as follows.

In [3]:
print(matrix1-matrix2)


[[-4 -4]
 [-4 -4]]


>**task**

Evalute `M=5 matrix1-& matrix2`

## Scalar Multiplication


In [4]:
# Scalar Multiplication
matrix = np.array([[1, 2], [3, 4]])
print(2 * matrix) # prints [[2, 4], [6, 8]]

[[2 4]
 [6 8]]


>**Task**
1. Create a $5\times5$ Random Matrix
2. calculate $5A-3I$

In [5]:
A=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[1,2,3,4,5]])
M3=5*A-3*np.eye(5)
print("the resultant matrix is")
print(M3)

the resultant matrix is
[[ 2. 10. 15. 20. 25.]
 [10. 12. 20. 25. 30.]
 [15. 20. 22. 30. 35.]
 [20. 25. 30. 32. 40.]
 [ 5. 10. 15. 20. 22.]]


## Matrix Multiplication

In [6]:
# Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2)) # prints [[19, 22], [43, 50]]

[[19 22]
 [43 50]]


## Matrix Hadamards product


In [7]:
# Matrix Hadamards product
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1*matrix2) 

[[ 5 12]
 [21 32]]


## Transpose

In [8]:
# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(np.transpose(matrix)) # prints [[1, 4], [2, 5], [3, 6]]

[[1 4]
 [2 5]
 [3 6]]


## Inverse of a matrix

In [5]:
# inverse of a matrix
a = np.array([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a)
print(a_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


>**Task**  
Find the inverse of a rectangular matrix  
ps: Pseudoinverse

In [10]:
# inverse of a matrix
b = np.array([[1, 2,3,1], [3, 1,1,5], [8,1,7,6]])
b_inv = np.linalg.pinv(b)
print(b_inv)

[[-0.19401198 -0.07245509  0.13113772]
 [ 0.3508982   0.13413174 -0.13532934]
 [ 0.15928144 -0.14730539  0.06826347]
 [ 0.01437126  0.24610778 -0.06526946]]


## Finding the cross products of two vectors
Let $\vec(v) \text( and ) \vec(u)$ be two vectors ,then the cross product is defined as
$$\vec(v)\times \vec(u)

In [11]:
# Cross Product
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print(np.cross(vector1, vector2)) # prints [-3, 6, -3]

[-3  6 -3]


:::{.callout-note}
## Note:

Norm: The norm of a vector is a scalar that represents the “length” of the vector. In NumPy, we can compute the norm using the numpy.linalg.norm function. The inner product of two vectors is a matrix that is computed by multiplying the first vector by the transpose of the second vector. In NumPy, we can compute the inner product using the numpy.inner function.

:::

## Finding norm

In [12]:
# finding norm
vector=np.array([1, 2, 3])
print(np.linalg.norm(vector)) # prints 3.74165738677

3.7416573867739413


## Inner product

In [13]:
#finding inner product
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print(np.inner(vector1, vector2)) # prints 32

32


## Determinant  
Find the determinat of a matrix

In [14]:
A = np.array([[1, 2], [3, 4]])

# Compute determinant
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


## System of equations  
The `np.linalg.solve()` function solves a linear matrix equation or system of linear scalar equations. It finds the vector x that satisfies 
. Syntax for this function is `np.linalg.solve(A, b)`.

In [15]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# Solve system of equations
x = np.linalg.solve(A, b)
print(x)

[2. 3.]


In [16]:
#import scipy
import numpy as np # for matrix definition
from scipy import linalg
#print(scipy.__version__) # check version

In [17]:
# example
A = np.array([[1, 2], [3, 4]])
det_A = linalg.det(A)
print(det_A)

-2.0


##  Solving Linear Systems of Equations  
One of the fundamental tasks in linear algebra is solving a system of linear equations of the form $AX = b$,where $A$ is a matrix and $b$ is a vector or matrix pf known values.

In [18]:
#example
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = linalg.solve(A, b)
print(x)

[2. 3.]


## Eigenvalues and Eigenvectors  
Eigenvalues and eigenvectors are fundamental in many areas of linear algebra, including solving systems of differential equations and performing dimensionality reduction in machine learning.


>**Syntax**: `scipy.linalg.eig(A)`

In [19]:
A = np.array([[3, 2], [4, 1]])
eigenvalues, eigenvectors = linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [ 5.+0.j -1.+0.j]
Eigenvectors: [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


## Sparse Matrices  
Sparse matrices are often useful in numerical simulations dealing with large systems, if the problem can be described in matrix form where the matrices or vectors mostly contains zeros. Scipy has a good support for sparse matrices, with basic linear algebra operations (such as equation solving, eigenvalue calculations, etc.).

There are many possible strategies for storing sparse matrices in an efficient way. Some of the most common are the so-called coordinate form (COO), list of list (LIL) form, and compressed-sparse column CSC (and row, CSR). Each format has some advantages and disadvantages. Most computational algorithms (equation solving, matrix-matrix multiplication, etc.) can be efficiently implemented using CSR or CSC formats, but they are not so intuitive and not so easy to initialize. So often a sparse matrix is initially created in COO or LIL format (where we can efficiently add elements to the sparse matrix data), and then converted to CSC or CSR before used in real calculations.